# Sin valores de desarrollo ni posibilidad de habilitar X-Demo-* en AWS.
app.security.enabled=true
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
app.security.issuer-uri=${COGNITO_ISSUER_URI}
app.security.client-id=${COGNITO_CLIENT_ID}

spring.flyway.enabled=false
